### ISSUE TITLE
Collection of flow statistics breaks RPC connection

### ISSUE THREAD

**Issue by ndavey** [ndavey/srx-wanmon#8]
During the flow collection RPC call the connection to the device times out/breaks

Could be too aggressive a monitoring interval
 - Consider starting a connection that is aggressive for counters and slow for sessions.

**Comment by ndavey** [comment]
This is the exception... Need to catch it, close the RPC, and then start a new connection.

Traceback (most recent call last):
  File "./app.py", line 86, in sessionLoop
    device_sessions = collectSessions (device)
  File "./app.py", line 67, in collectSessions
    device_sessions["st0.0"] = if_fw_states(device, "st0.0")
  File "/vol-sdwan_web/srx_wanmon_utils.py", line 74, in if_fw_states
    collect_fw_states = device_connection.rpc.get_flow_session_information(interface=ifName)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/rpcmeta.py", line 156, in _exec_rpc
    return self._junos.execute(rpc, **dec_args)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 71, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/decorators.py", line 26, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jnpr/junos/device.py", line 520, in execute
    raise EzErrors.RpcTimeoutError(self, rpc_cmd_e.tag, self.timeout)
jnpr.junos.exception.RpcTimeoutError: RpcTimeoutError(host: 10.164.0.243, cmd: get-flow-session-information, timeout: 30)
Unhandled exception in thread started by <function statLoop at 0x7f208462d578>

**Comment by ndavey** [comment]
Catching the exception doesn't help. Session info gathering now uses it's own dedicated Device. Need to increase the time-out on this device to prevent this issue.

If that doesn't work this feature will be ELIMINATED!
